on:
  workflow_call:
    inputs:
      device-group:
        description: Device group to which to deploy the artifact, or skip deployment if not defined.
        default: ''
        required: false
        type: string
      device-type:
        description: Device type for the artifact.
        required: true
        type: string
      manifest-file:
        description: Path to the manifest file for which to generate the artifact (e.g., docker-compose.yaml).
        required: true
        type: string
      mender-host:
        description: Mender host URL for artifact upload and deployment.
        default: ''
        required: false
        type: string
      platform:
        description: Platform with which the artifact is compatible (e.g., linux/arm/v7).
        required: true
        type: string
      service-images:
        description: Image name overrides for services in the manifest_file, as a JSON array ["<service>=<image>", "<service>=<image>", ...].
        default: ''
        required: false
        type: string
      helper-image:
        description: Docker image to use as mender-docker-lifecycle-helper.
        default: 'ghcr.io/rcwbr/mender-docker-lifecycle-helper:0.3.0'
        required: false
        type: string
    secrets:
      mender-pat-secret:
        description: Secret that contains the Mender server Personal Access Token to use for artifact upload and deployment.
        required: true
jobs:
  mender-docker-lifecycle-helper:
    name: Mender Docker Lifecycle Helper${{ matrix.release && ' release' || '' }} - ${{ matrix.delta && 'delta' }}
    strategy:
      matrix:
        delta: [ true, false ]
        release:
          - ${{ github.ref_type == 'tag' }}
        # Never run as non-delta if not a release
        exclude:
          - delta: false
            release: false
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.helper-image }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          # Needed for pull_request workflow types
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      -
        name: "mender-docker-lifecycle-helper"
        shell: bash
        env:
          MENDER_PAT: ${{ secrets.mender-pat-secret }}
        run: |
          mender-docker-lifecycle-helper \
            --platform ${{ inputs.platform }} \
            --device-type ${{ inputs.device-type }} \
            --delta ${{ matrix.delta }} \
            ${{ matrix.release && '--release' || '' }} \
            ${{ inputs.device-group && format('--device-group {0}', inputs.device-group) || '' }} \
            ${{ inputs.mender-host && format('--mender-host {0}', inputs.mender-host) || '' }} \
            ${{ inputs.service-images && format('--service-image {0}', join(fromJSON(inputs.service-images), '--service-image')) || '' }} \
            ${{ inputs.manifest-file }}
